[project]
name = "flights-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "psycopg[binary]>=3.2.7",
    "pycountry>=24.6.1",
    "pydantic-extra-types>=2.10.4",
    "pytest>=8.3.5",
    "redis>=6.0.0",
    "sqlalchemy>=2.0.40",
]
